Iter13
stsg/shorty pull request #13
Opened 2024-01-17 20:01 UTC by stsg

2024-01-22 16:08 UTC, rktkov requested changes

2024-01-22 16:08 UTC, rktkov commented on internal/storage/dbstorage.go
> +func (s *DBStorage) IsShortURLExist(shortURL string) bool {
Не увидел (может это было в предыдущих ПР, тогда комментарий можно дальше не читать) использование этого метода и следующего где-то еще кроме пакета storage. Если это так, то стоит их сделать закрытыми.

2024-01-22 16:08 UTC, rktkov commented on internal/storage/dbstorage.go
> +	var shortURL string
Тут потенциальное место для снижения производительности базы.
Возможно нарушение уникальности пары long-short между вызовом метода на строчке 85 и 86 при параллельном исполнении запросов. Стоит тут использовать механизм транзакций, для гарантия уникальности после проверки.

2024-01-22 16:08 UTC, rktkov commented on internal/handle/handle.go
> +		shortURL, err := h.storage.GetShortURL(rqElemJSON.URL)
Я бы подумал, как добавить в хранилище метод сохранения одновременно нескольких пар long-short url - чтобы уменьшить количество запросов в БД.

2024-01-24 10:43 UTC, stsg commented on internal/storage/dbstorage.go
> +	"github.com/golang-migrate/migrate/v4"
Fixed

2024-01-24 10:43 UTC, stsg commented on internal/storage/dbstorage.go
> +func (s *DBStorage) IsShortURLExist(shortURL string) bool {
Используется в функциях тестирования

2024-01-24 10:45 UTC, stsg commented on internal/storage/dbstorage.go
> +	var shortURL string
Дельное замечание! ;) Fixed.

2024-01-24 10:46 UTC, stsg commented on internal/handle/handle.go
> +		shortURL, err := h.storage.GetShortURL(rqElemJSON.URL)
Пока не вижу особых преимуществ, за исключением использования транзакции. Fixed.

2024-01-26 11:20 UTC, rktkov approved these changes

2024-01-27 18:32 UTC, merged