Iter25
stsg/shorty pull request #28
Opened 2024-05-07 13:22 UTC by stsg

iter25

2024-05-14 12:17 UTC, tmvrus requested changes
- неуместное использование panic
- не все ошибки проверяются
- нет тестов на новую функциональность

2024-05-14 12:17 UTC, tmvrus commented on Makefile
> +protoc:
https://github.com/uber/prototool упрощает работу

2024-05-14 12:17 UTC, tmvrus commented on api/shortener.proto
> +  bool is_unique_error = 2;
так делать не рекомендуется, у grpc есть набор status codes для ошибок, которые можно расширять

2024-05-14 12:17 UTC, tmvrus commented on api/shortener.proto
> +  bool is_url_deleted = 2;
тоже самое

2024-05-14 12:17 UTC, tmvrus commented on internal/app/handlers.go
> +		panic(errors.New("cannot read request body"))
из-за одной ошибки уронить все приложение?

2024-05-14 12:17 UTC, tmvrus commented on internal/app/handlers.go
> +	}
лучше наоборот, сначала err != nil просто потому что так делают существенно чаще

2024-05-14 12:17 UTC, tmvrus commented on internal/app/handlers.go
> +	// body, _ := json.Marshal(resJSON)
закоменечного кода в рабочем проекте быть не должно, это дурной тон

2024-05-14 12:17 UTC, tmvrus commented on internal/app/handlers.go
> +		rw.Write([]byte(err.Error()))
для этого есть хелпер http.Error

2024-05-14 20:36 UTC, stsg commented on Makefile
> +protoc:
fixed

2024-05-14 20:38 UTC, stsg commented on api/shortener.proto
> +  bool is_url_deleted = 2;
fixed

2024-05-14 20:38 UTC, stsg commented on internal/app/handlers.go
> +		panic(errors.New("cannot read request body"))
fixed

2024-05-14 20:41 UTC, stsg commented on internal/app/handlers.go
> +	}
fixed

2024-05-14 20:42 UTC, stsg commented on internal/app/handlers.go
> +	// body, _ := json.Marshal(resJSON)
fixed

2024-05-14 20:43 UTC, stsg commented on internal/app/handlers.go
> +		rw.Write([]byte(err.Error()))
fixed

2024-05-17 15:24 UTC, tmvrus approved these changes

2024-05-17 15:24 UTC, tmvrus commented on api/v1/shorty.proto
> +  // bool is_url_deleted = 2;
дурной тон

2024-05-17 15:24 UTC, tmvrus commented on api/v1/shorty.proto
> +  // bool is_unique_error = 2;
дурной тон

2024-05-17 15:24 UTC, tmvrus commented on api/v1/shorty.proto
> +  string error = 2;
нет никакого смысла хранить ошибку тут
для нее в протоколе отведено свое место

2024-05-18 08:55 UTC, merged